### ISSUE TITLE
Remove SlicerPython launcher

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4849]
Edit the file `python_configure_python_launcher.cmake` removing the configuration of `SlicerPython` launcher:

https://github.com/Slicer/Slicer/blob/d9c5ba6cf5641cdac7289d37b7238d2c1fd741d4/SuperBuild/python_configure_python_launcher.cmake#L173-L184

Background:
* https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Slicer_5.0%3A_SlicerPython_was_removed._Use_PythonSlicer_instead
* https://github.com/Slicer/Slicer/issues/4843

**Comment by hjmjohnson** [comment]
@jcfr I don't know if this is related, but Ubuntu 18.04 build is having troubles

```
'/user/iibi/johnsonhj/src/Slicer-clang11/python-install/bin/PythonSlicer' '-m' 'ensurepip' '--default-pip'
Exception:
Traceback (most recent call last):
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 241, in run
    with self._build_session(options) as session:
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_internal/download.py", line 101, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/tmp/tmpvl0ov37x/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/user/iibi/johnsonhj/src/Slicer-clang11/python-install/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/user/iibi/johnsonhj/src/Slicer-clang11/python-install/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
```
