### ISSUE TITLE
I can't pip-install the noise library

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#4954]
When I try to use `slicer.util.pip_install` to install the `noise` library, I get an error: `'Python.h' file not found`. I think I've managed to install it in earlier Slicer versions.

## Steps to reproduce

```python-traceback
>>> pip_install('noise')
Collecting noise
  Using cached noise-1.2.2.tar.gz (125 kB)
Building wheels for collected packages: noise
  Building wheel for noise (setup.py): started
  Building wheel for noise (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Applications/Slicer.app/Contents/bin/./python-real -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"'; __file__='"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-wheel-qpoxb23l
       cwd: /private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-3.6
  creating build/lib.macosx-10.11-x86_64-3.6/noise
  copying shader.py -> build/lib.macosx-10.11-x86_64-3.6/noise
  copying perlin.py -> build/lib.macosx-10.11-x86_64-3.6/noise
  copying shader_noise.py -> build/lib.macosx-10.11-x86_64-3.6/noise
  copying __init__.py -> build/lib.macosx-10.11-x86_64-3.6/noise
  copying test.py -> build/lib.macosx-10.11-x86_64-3.6/noise
  running build_ext
  building 'noise._simplex' extension
  creating build/temp.macosx-10.11-x86_64-3.6
  /usr/bin/clang -pthread -Wall -g -fPIC -I/Applications/Slicer.app/Contents/lib/Python/include/python3.6m -c _simplex.c -o build/temp.macosx-10.11-x86_64-3.6/_simplex.o -funroll-loops
  _simplex.c:5:10: fatal error: 'Python.h' file not found
  #include "Python.h"
           ^~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for noise
  Running setup.py clean for noise
Failed to build noise
Installing collected packages: noise
    Running setup.py install for noise: started
    Running setup.py install for noise: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Applications/Slicer.app/Contents/bin/./python-real -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"'; __file__='"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-record-3p3p4ga3/install-record.txt --single-version-externally-managed --compile --install-headers /Applications/Slicer.app/Contents/lib/Python/include/python3.6m/noise
         cwd: /private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-3.6
    creating build/lib.macosx-10.11-x86_64-3.6/noise
    copying shader.py -> build/lib.macosx-10.11-x86_64-3.6/noise
    copying perlin.py -> build/lib.macosx-10.11-x86_64-3.6/noise
    copying shader_noise.py -> build/lib.macosx-10.11-x86_64-3.6/noise
    copying __init__.py -> build/lib.macosx-10.11-x86_64-3.6/noise
    copying test.py -> build/lib.macosx-10.11-x86_64-3.6/noise
    running build_ext
    building 'noise._simplex' extension
    creating build/temp.macosx-10.11-x86_64-3.6
    /usr/bin/clang -pthread -Wall -g -fPIC -I/Applications/Slicer.app/Contents/lib/Python/include/python3.6m -c _simplex.c -o build/temp.macosx-10.11-x86_64-3.6/_simplex.o -funroll-loops
    _simplex.c:5:10: fatal error: 'Python.h' file not found
    #include "Python.h"
             ^~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Slicer.app/Contents/bin/./python-real -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"'; __file__='"'"'/private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-install-0lrrf0ns/noise/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tk/sq0b7n6j5hz_lv9n0gnqdcsc0000gn/T/pip-record-3p3p4ga3/install-record.txt --single-version-externally-managed --compile --install-headers /Applications/Slicer.app/Contents/lib/Python/include/python3.6m/noise Check the logs for full command output.
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/Applications/Slicer.app/Contents/bin/./python-real -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 2335, in pip_install
    logProcessOutput(proc)
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 2288, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer.app/Contents/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'noise']' returned non-zero exit status 1.
```

## Environment
- Slicer version: Slicer-4.11.0-2020-05-28
- Operating system: macOS Catalina 10.15.4.

**Comment by jamesobutler** [comment]
Can you try installing it in a regular python install and not the one with Slicer and report back your results?

Looking at https://github.com/caseman/noise/issues another person had problems building the wheel during install on Windows.  The module doesn’t have prebuilt wheels for the latest versions of Python on PyPi so it’s probably not a well maintained module.

**Comment by fepegar** [comment]
It seems to work on Python 3.8:

```
$ conda create -n noise python ipython -y && conda activate noise               
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/noise

  added / updated specs:
    - ipython
    - python


The following NEW packages will be INSTALLED:

  appnope            pkgs/main/osx-64::appnope-0.1.0-py38_0
  backcall           pkgs/main/osx-64::backcall-0.1.0-py38_0
  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/osx-64::certifi-2020.4.5.1-py38_0
  decorator          pkgs/main/noarch::decorator-4.4.2-py_0
  ipython            pkgs/main/osx-64::ipython-7.13.0-py38h5ca1d4c_0
  ipython_genutils   pkgs/main/osx-64::ipython_genutils-0.2.0-py38_0
  jedi               pkgs/main/osx-64::jedi-0.17.0-py38_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.3-h0a44026_1
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1g-h1de35cc_0
  parso              pkgs/main/noarch::parso-0.7.0-py_0
  pexpect            pkgs/main/osx-64::pexpect-4.8.0-py38_0
  pickleshare        pkgs/main/osx-64::pickleshare-0.7.5-py38_1000
  pip                pkgs/main/osx-64::pip-20.0.2-py38_3
  prompt-toolkit     pkgs/main/noarch::prompt-toolkit-3.0.4-py_0
  prompt_toolkit     pkgs/main/noarch::prompt_toolkit-3.0.4-0
  ptyprocess         pkgs/main/osx-64::ptyprocess-0.6.0-py38_0
  pygments           pkgs/main/noarch::pygments-2.6.1-py_0
  python             pkgs/main/osx-64::python-3.8.3-h26836e1_1
  readline           pkgs/main/osx-64::readline-8.0-h1de35cc_0
  setuptools         pkgs/main/osx-64::setuptools-46.4.0-py38_0
  six                pkgs/main/osx-64::six-1.14.0-py38_0
  sqlite             pkgs/main/osx-64::sqlite-3.31.1-h5c1f38d_1
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  traitlets          pkgs/main/osx-64::traitlets-4.3.3-py38_0
  wcwidth            pkgs/main/noarch::wcwidth-0.1.9-py_0
  wheel              pkgs/main/osx-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate noise
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ pip install noise                                                                  
Processing /Users/fernando/Library/Caches/pip/wheels/b3/e1/a8/cf0ce54c603bc4e4965e354a7aa3d8dacb8714f2c2db82ba04/noise-1.2.2-cp38-cp38-macosx_10_9_x86_64.whl
Installing collected packages: noise
Successfully installed noise-1.2.2

$ python -c "import noise; print(noise.__version__)"        
1.2.1
```

**Comment by fepegar** [comment]
Works on Python 3.6 too.

**Comment by jamesobutler** [comment]
Can you try installing using pip in regular python install instead of a Conda install?

**Comment by fepegar** [comment]
What do you mean by "regular python install"? At the moment, Python defaults to the `conda` one in my computer. I don't even have `pip` installed in my OS. Isn't this the cleanest way to try this stuff? That's one of the points of being able to use virtual environments.

**Comment by fepegar** [comment]
Also, in this case I'm using `conda` only as a virtual env manager. Then I use `pip` to install the package, not `conda`.

**Comment by jamesobutler** [comment]
Just trying to match As much as possible the standard python environment with the one used in Slicer.
https://www.python.org/downloads/release/python-367/

**Comment by fepegar** [comment]
Works fine on `3.6.7` and `3.6.10`.

**Comment by lassoan** [comment]
It seems that no Python wheels are available for this package for Python 3.6.7. For me, missing Python wheels for mainstream platforms is always a big warning sign, which indicates that the package is obsolete, neglected, or not high on their maintainers' priority list. The noise project's repository (https://github.com/caseman/noise) confirms that it is not in good health, it does not have a promising future.

You can probably find better alternatives, which offer the same features but they are more stable, better supported, and overall better quality (and have wheels, too).

**Comment by fepegar** [comment]
How did you check whether the wheels were not available? I can install it from Python 3.6.7:

```
 Py 3.6.7 (noise)  ~  pip install noise      
Processing ./Library/Caches/pip/wheels/23/38/b7/504656d18f000db42b567933cd9864f66ec8d7ba17292af811/noise-1.2.2-cp36-cp36m-macosx_10_9_x86_64.whl
Installing collected packages: noise
Successfully installed noise-1.2.2
```

[There are indeed better alternatives](https://github.com/lmas/opensimplex), but I started a project using that specific library and would like to continue using it, if possible.

**Comment by jamesobutler** [comment]
I think @lassoan is referring to this location in PyPI to check what files are available https://pypi.org/project/noise/#files.  Essentially with this module its pulling source and then having to build the wheel locally and then installing it.  From the debugging done, the python in Slicer is struggling to build the source into the wheel which has success in python outside of Slicer.

**Comment by lassoan** [comment]
If you get a message that Python.h is not found then it means that the package had to be built, which means that wheels were not found.

**Comment by fepegar** [comment]
I just tried again in Slicer and it worked:

```
Processing /Users/fernando/Library/Caches/pip/wheels/23/38/b7/504656d18f000db42b567933cd9864f66ec8d7ba17292af811/noise-1.2.2-cp36-cp36m-macosx_10_9_x86_64.whl
Installing collected packages: noise
Successfully installed noise-1.2.2
```

I can investigate further if you like. It looks like maybe Slicer is not able to build the wheel, but this time it found an already built one on my computer, so it used that one. It must be the one that was built when I tried installing with Python 3.6.7 outside Slicer.

**Comment by jcfr** [comment]
For reference, this package would need to be updated to use something like https://scikit-build.readthedocs.io along with an updated CI infrastructure.

**Comment by fepegar** [comment]
I mentioned this issue in the repo, but it does look quite inactive.
