### ISSUE TITLE
AttributeError: 'PythonQtStdInRedirect' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5705]
I am trying to use the [`light-the-torch`](https://github.com/pmeier/light-the-torch) Python package within Slicer, in the context of [my PW35 Project](https://github.com/NA-MIC/ProjectWeek/tree/master/PW35_2021_Virtual/Projects/PyTorchIntegration). When I try to import it from the Python console, I get the following:

```python-traceback
>>> import light_the_torch as ltt
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/light_the_torch/__init__.py", line 3, in <module>
    from ._pip import *
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/light_the_torch/_pip/__init__.py", line 1, in <module>
    from .extract import *
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/light_the_torch/_pip/extract.py", line 5, in <module>
    from pip._internal.req.req_install import InstallRequirement
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 10, in <module>
    from .req_install import InstallRequirement
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 35, in <module>
    from pip._internal.utils.direct_url_helpers import direct_url_from_link
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/utils/direct_url_helpers.py", line 12, in <module>
    from pip._internal.vcs import vcs
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/vcs/__init__.py", line 9, in <module>
    import pip._internal.vcs.subversion  # noqa: F401
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/vcs/subversion.py", line 336, in <module>
    vcs.register(Subversion)
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/vcs/versioncontrol.py", line 317, in register
    self._registry[cls.name] = cls()
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/vcs/subversion.py", line 191, in __init__
    use_interactive = is_console_interactive()
  File "/home/fernando/opt/Slicer/Nightly/lib/Python/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 906, in is_console_interactive
    return sys.stdin is not None and sys.stdin.isatty()
AttributeError: 'PythonQtStdInRedirect' object has no attribute 'isatty'
```

## Steps to reproduce

```python
>>> from pip._internal.req.req_install import InstallRequirement
```

or just

```python
>>> import sys
>>> sys.stdin
<PythonQtStdInRedirect object at 0x7f0f5458ddf0>
>>> sys.stdin.isatty()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'PythonQtStdInRedirect' object has no attribute 'isatty'
```

## Expected behavior

I suppose I expect what I get in Python outside of Slicer:

```python
>>> import sys
>>> sys.stdin
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
>>> sys.stdin.isatty()
True
```

## Environment
- Slicer version: Slicer-4.13.0-2021-06-22
- Operating system: Ubuntu 18.04.04 LTS

**Comment by pieper** [comment]
Thanks for the report - we should find a way to implement that method to avoid the error, although if this package expects stdin to act like a console there may be other issues.  The fix could go in [the ctk fork](https://github.com/commontk/PythonQt) or eventually in [the upstream project](https://mevislab.github.io/pythonqt/).  @jcfr is the expert here.

(For historical reference tty is short for teletype)

**Comment by lassoan** [comment]
If you search for `isatty` in pip source code then you can find lots of ugly hacks. The particular one that you have run into seems to be added to accommodate some old Subversion clients.

Anyway, these hacks in pip will not be cleaned up for a while, so I agree it is just easier to comply with whatever pip expects.

`isatty` is implemented in PythonQt for stdout: https://github.com/MeVisLab/pythonqt/blob/master/src/PythonQtStdOut.cpp#L115

I'm not sure if leaving it out from stdin is intentional or not, but you could probably implement it by adding the same code to stdin:

https://github.com/MeVisLab/pythonqt/blob/master/src/PythonQtStdIn.cpp

@fepegar could you give this a try?

**Comment by fepegar** [comment]
> @fepegar could you give this a try?

I'm not that familiar with CPP, but it looks feasible. Thanks for your feedback and guidance, @pieper and @lassoan.

**Comment by lassoan** [comment]
@fepegar you were fast! Have you checked if the method works and fixes the issue? If you don't have a Slicer build then let me know and I can test it for you.

**Comment by fepegar** [comment]
I haven't checked (I just copied the pattern in `PythonQtStdOut` to `PythonQtStdIn`) and I don't have a Slicer build at the moment. It would be great if you could try this.

**Comment by lassoan** [comment]
The patch has been merged into PythonQt upstream.

@jcfr can I just backport that single commit into Slicer's fork?

**Comment by jcfr** [comment]
> can I just backport that single commit into Slicer's PythonQt fork?

Indeed, here are the steps:

1. Backport to branch https://github.com/commontk/PythonQt/commits/patched-10  (commit message should be amended to be `[Backport] Add isatty() method to PythonQtStdIn class `
2. Update CTK (see https://github.com/commontk/CTK/blob/9f12861724155f9929de9be8500c9eabd38507ac/CMakeExternals/PythonQt.cmake#L85)
3. Update CTK version used in Slicer

**Comment by jcfr** [comment]
as a side note, it seems that `patched-9` and `patched-10` are identical branch. I think we could remove `patched-10` (and updated comment [here](https://github.com/commontk/CTK/blob/9f12861724155f9929de9be8500c9eabd38507ac/CMakeExternals/PythonQt.cmake#L85)) but this would have to be verified
