### ISSUE TITLE
OSError in DicomUtils script

### ISSUE THREAD

**Issue by ferdymercury** [Slicer/Slicer#5850]
```
Traceback (most recent call last):
  File "<string>", line 400, in main
  File "/opt/Slicer-4.13.0-2021-09-13-linux-amd64/lib/Slicer-4.13/qt-scripted-modules/DICOMLib/DICOMUtils.py", line 66, in loadPatientByUID
    raise OSError('No studies found in patient with DICOM database UID ' + patientUIDstr)
OSError: No studies found in patient with DICOM database UID 2
No studies found in patient with DICOM database UID 2
```
## Steps to reproduce

```
/opt/Slicer-4.13.0-2021-09-13-linux-amd64/Slicer --no-main-window --python-script /opt/SlicerRT_github-repo/BatchProcessing/BatchStructureSetConversion.py --input-folder /home/user/Desktop/dicom --output-folder /tmp
qSlicerSequencesModulePrivate::addToolBar: no main window is available, toolbar is not added
Start batch RTSTRUCT conversion
BatchStructureSet running in file mode
Import DICOM data from /home/user/Desktop/dicom
Switching to temporary DICOM database: /tmp/Slicer-user/20210914_094216_TempDICOMDatabase
TagCacheDatabase adding table

"DICOM indexer has successfully inserted 47 files [0.02s]"
"DICOM indexer has successfully processed 47 files [0.04s]"
"DICOM indexer has updated display fields for 47 files [0.01s]"
Processing 2 patients...
W: OperatorsName (0008,1070) absent in RTSeriesModule (type 2)
Loading with imageIOName: GDCM
W: OperatorsName (0008,1070) absent in RTSeriesModule (type 2)
LoadContour: Contour image sequence object item in referenced frame of reference sequence is invalid


LoadContour: Contour image sequence object item in referenced frame of reference sequence is invalid


LoadContour: Contour image sequence object item in referenced frame of reference sequence is invalid


Convert loaded structure set to labelmap volumes
  Converting structure set 1: RTSTRUCT: OCP RTS v4.1.6 to labelmap
CalculateOutputGeometry: No image geometry specified, default geometry is calculated (0.16831485670448637;0;0;-94.85015106201172;0;0.16831485670448637;0;-64.8306655883789;0;0;0.16831485670448637;-38.5;0;0;0;1;0;302;0;223;0;231;)


CalculateOutputGeometry: No image geometry specified, default geometry is calculated (0.06009535476705829;0;0;-72.81781005859375;0;0.06009535476705829;0;-47.516971588134766;0;0;0.06009535476705829;-40.5;0;0;0;1;0;116;0;186;0;715;)


CalculateOutputGeometry: No image geometry specified, default geometry is calculated (0.11700710695582281;0;0;-84.82732391357422;0;0.11700710695582281;0;-78.04917907714844;0;0;0.11700710695582281;-41.5;0;0;0;1;0;324;0;125;0;384;)


Save labelmaps to directory /tmp/1
  Saving structure 1: RTSTRUCT: OCP RTS v4.1.6_Target
    to file 1 RTSTRUCT OCP RTS v4.1.6_Target.nrrd
Generic Warning: In /work/Preview/Slicer-0/Libs/MRML/Core/vtkDataFileFormatHelper.cxx, line 237
vtkDataFileFormatHelper::GetFileExtensionFromFormatString: please update deprecated extension-only format specifier to 'File format name (.ext)' format! Current format string: .nrrd


WriteData: removing old version of file /tmp/1/1 RTSTRUCT OCP RTS v4.1.6_Target.nrrd


  Saving structure 1: RTSTRUCT: OCP RTS v4.1.6_urethra
    to file 1 RTSTRUCT OCP RTS v4.1.6_urethra.nrrd
Generic Warning: In /work/Preview/Slicer-0/Libs/MRML/Core/vtkDataFileFormatHelper.cxx, line 237
vtkDataFileFormatHelper::GetFileExtensionFromFormatString: please update deprecated extension-only format specifier to 'File format name (.ext)' format! Current format string: .nrrd


WriteData: removing old version of file /tmp/1/1 RTSTRUCT OCP RTS v4.1.6_urethra.nrrd


  Saving structure 1: RTSTRUCT: OCP RTS v4.1.6_rectum
    to file 1 RTSTRUCT OCP RTS v4.1.6_rectum.nrrd
Generic Warning: In /work/Preview/Slicer-0/Libs/MRML/Core/vtkDataFileFormatHelper.cxx, line 237
vtkDataFileFormatHelper::GetFileExtensionFromFormatString: please update deprecated extension-only format specifier to 'File format name (.ext)' format! Current format string: .nrrd


WriteData: removing old version of file /tmp/1/1 RTSTRUCT OCP RTS v4.1.6_rectum.nrrd


DONE
Traceback (most recent call last):
  File "<string>", line 400, in main
  File "/opt/Slicer-4.13.0-2021-09-13-linux-amd64/lib/Slicer-4.13/qt-scripted-modules/DICOMLib/DICOMUtils.py", line 66, in loadPatientByUID
    raise OSError('No studies found in patient with DICOM database UID ' + patientUIDstr)
OSError: No studies found in patient with DICOM database UID 2
No studies found in patient with DICOM database UID 2
```

## Expected behavior

A second patient is created even if there is only one patient. Later it tries to access it.

## Environment
- Slicer version: Slicer-4.13.0-2021-09-13
- Operating system: Ubuntu 19

**Comment by ferdymercury** [comment]
Database via the GUI only shows 1 patient:
![image](https://user-images.githubusercontent.com/10653970/133238684-89918963-17e8-41e8-aa89-f42e1a24fd46.png)

**Comment by lassoan** [comment]
Can you provide a sample data set that we could reproduce the issue with?

**Comment by ferdymercury** [comment]
Please find attached.

[testfiles.zip](https://github.com/Slicer/Slicer/files/7215788/testfiles.zip)

**Comment by lassoan** [comment]
The issue was that the same study instance was used with different patient name and ID. This made a patient appear in the database that did not have any associated studies. The BatchStructureSetConversion script stopped with an error when encountered an empty patient.

It would be probably better to fix this in the input DICOM data, but I've updated the BatchStructureSetConversion script to be more tolerant - if an empty patient is found then it now just skips that.

**Comment by ferdymercury** [comment]
Thanks so much!
