### ISSUE TITLE
Qt Designer crashes when it is launched by the Slicer launcher (./Slicer --designer)

### ISSUE THREAD

**Issue by RafaelPalomar** [Slicer/Slicer#6167]
Qt Designer crashes when invoked through Slicer with the following output:

```
Designer: The class attribute for the class qSlicerDiffusionTensorVolumeDisplayWidgetPlugin does not match the class name qSlicerDiffusionTensorVolumeDisplayWidget.
This function is deprecated. Use currentNodeID() instead
qMRMLNodeComboBox::baseName failed: no node types have been set yet
QMetaProperty::read: Unable to handle unregistered datatype 'QComboBox::SizeAdjustPolicy' for property 'qMRMLNodeComboBox::sizeAdjustPolicy'
QMetaProperty::read: Unable to handle unregistered datatype 'QFrame::Shape' for property 'ctkCollapsibleButton::contentsFrameShape'
QMetaProperty::read: Unable to handle unregistered datatype 'QFrame::Shadow' for property 'ctkCollapsibleButton::contentsFrameShadow'
This function is deprecated. Use currentNodeID() instead
qMRMLNodeFactory::baseName failed: class name vtkMRMLColorTableNode not found
QMetaProperty::read: Unable to handle unregistered datatype 'QComboBox::SizeAdjustPolicy' for property 'qMRMLNodeComboBox::sizeAdjustPolicy'
This function is deprecated. Use currentNodeID() instead
QMetaProperty::read: Unable to handle unregistered datatype 'QComboBox::SizeAdjustPolicy' for property 'qMRMLNodeComboBox::sizeAdjustPolicy'
QObject::connect: No such slot qMRMLDisplayNodeWidget::set3DVisible(bool) in /home/rafael/src/Slicer/Slicer-master/Libs/MRML/Widgets/qMRMLDisplayNodeWidget.cxx:72
QObject::connect:  (sender name:   'ThreeDVisibilityCheckBox')
QObject::connect:  (receiver name: 'qMRMLDisplayNodeWidget')
QMetaProperty::read: Unable to handle unregistered datatype 'QSlider::TickPosition' for property 'ctkSliderWidget::tickPosition'
This function is deprecated. Use currentNodeID() instead
qMRMLNodeComboBox::baseName failed: no node types have been set yet
QMetaProperty::read: Unable to handle unregistered datatype 'QComboBox::SizeAdjustPolicy' for property 'qMRMLNodeComboBox::sizeAdjustPolicy'
QString qMRMLPlotViewControllerWidget::viewLabel() const  failed: must set view node first
QMetaProperty::read: Unable to handle unregistered datatype 'vtkMRMLScene*' for property 'qMRMLRangeWidget::mrmlScene'
QMetaProperty::read: Unable to handle unregistered datatype 'vtkMRMLDisplayNode::ScalarRangeFlagType' for property 'qMRMLScalarsDisplayWidget::scalarRangeMode'
qMRMLSliceControllerWidget::setSliceViewName failed: MRMLSliceNode is invalid
QString qMRMLSliceControllerWidget::sliceViewLabel() const  failed: must set view node first
qMRMLSliceControllerWidget::setSliceViewName failed: MRMLSliceNode is invalid
QString qMRMLSliceControllerWidget::sliceViewLabel() const  failed: must set view node first
QMetaProperty::read: Unable to handle unregistered datatype 'QSlider::TickPosition' for property 'ctkSliderWidget::tickPosition'
qMRMLTableView:: bool qMRMLTableView::transposed() const  failed: invalid node
qMRMLTableView:: bool qMRMLTableView::firstRowLocked() const  failed: invalid node
qMRMLTableView:: bool qMRMLTableView::firstColumnLocked() const  failed: invalid node
virtual void qSlicerMarkupsPlaceWidget::setup() : Markups module is not found, some markup manipulation features will not be available
bool qSlicerMarkupsPlaceWidget::placeModePersistency() const  failed: interactionNode is invalid
qSlicerMarkupsPlaceWidget::deleteAllMarkupsOptionVisible method is deprecated, please use deleteAllControlPointsOptionVisible instead
virtual void qSlicerSimpleMarkupsWidget::setup() : Markups module is not found, some markup manipulation features will not be available
virtual void qSlicerMarkupsPlaceWidget::setup() : Markups module is not found, some markup manipulation features will not be available
virtual void qSlicerSimpleMarkupsWidget::setup() : Markups module is not found, some markup manipulation features will not be available
virtual void qSlicerMarkupsPlaceWidget::setup() : Markups module is not found, some markup manipulation features will not be available
error: [/usr/bin/designer] exit abnormally - Report the problem.
```

Here the coredump backtrace:

```
#0  0x00007f25c5d77a6d in QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> >::operator->() const (this=0x28) at /usr/include/qt5/QtCore/qscopedpointer.h:118
#1  0x00007f25c5d766ec in qGetPtrHelper<QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> > const>(QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> > const&) (ptr=...) at /usr/include/qt5/QtCore/qglobal.h:1143
#2  0x00007f25c5bc7d2d in qSlicerCoreApplication::d_func() const (this=0x0)
    at /home/rafael/src/Slicer/Slicer-master/Base/QTCore/qSlicerCoreApplication.h:648
#3  0x00007f25c5bc0b23 in qSlicerCoreApplication::userSettings() const (this=0x0)
    at /home/rafael/src/Slicer/Slicer-master/Base/QTCore/qSlicerCoreApplication.cxx:1167
#4  0x00007f25c55f1ed2 in qSlicerTerminologyNavigatorWidgetPrivate::init() (this=0x55d218ab1660)
    at /home/rafael/src/Slicer/Slicer-master/Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx:298
#5  0x00007f25c55f3de2 in qSlicerTerminologyNavigatorWidget::qSlicerTerminologyNavigatorWidget(QWidget*) (this=
    0x55d2188f0bf0, _parent=0x0)
    at /home/rafael/src/Slicer/Slicer-master/Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx:616
#6  0x00007f25c3e39168 in qSlicerTerminologyNavigatorWidgetPlugin::createWidget(QWidget*)
    (this=0x55d21811f6f0, parentWidget=0x0)
    at /home/rafael/src/Slicer/Slicer-master/Modules/Loadable/Terminologies/Widgets/DesignerPlugins/qSlicerTerminologyNavigatorWidgetPlugin.cxx:34
#7  0x00007f25f29966bd in qdesigner_internal::WidgetFactory::createCustomWidget(QString const&, QWidget*, bool*) const () at /usr/lib64/libQt5Designer.so.5
#8  0x00007f25f2996f58 in qdesigner_internal::WidgetFactory::createWidget(QString const&, QWidget*) const ()
    at /usr/lib64/libQt5Designer.so.5
#9  0x00007f25f299e6af in qdesigner_internal::WidgetDataBase::defaultPropertyValues(QString const&) ()
    at /usr/lib64/libQt5Designer.so.5
#10 0x00007f25f299e878 in qdesigner_internal::WidgetDataBase::grabDefaultPropertyValues() ()
    at /usr/lib64/libQt5Designer.so.5
#11 0x000055d2164aa663 in  ()
#12 0x000055d2164a3d7b in  ()
#13 0x000055d216490df7 in  ()
#14 0x00007f25f10317ed in __libc_start_main () at /lib64/libc.so.6
#15 0x000055d216490efa in  ()
```

## Steps to reproduce

`./Slicer --designer`

## Expected behavior

Qt Designer should open without problems

## Environment
- Slicer version: Slicer-4.13.0-2022-02-08
- Operating system:  Linux (Gentoo Linux)
- Qt Version: 5.15.2-r14 (Gentoo)

**Comment by RafaelPalomar** [comment]
I've tried slicer/slicer@9766f4f1f8fd85ed4d33e8f7ea39235b0334502d and get similar results. Here is the backtrace, which is slightly different:

```console
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffaf1822a69 in QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> >::operator-> (this=0x28)
    at /usr/include/qt5/QtCore/qscopedpointer.h:118
118	        return d;
--Type <RET> for more, q to quit, c to continue without paging--
[Current thread is 1 (Thread 0x7ffb18a5f600 (LWP 43703))]
(gdb) backtrac
#0  0x00007ffaf1822a69 in QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> >::operator-> (this=0x28)
    at /usr/include/qt5/QtCore/qscopedpointer.h:118
#1  0x00007ffaf18216e8 in qGetPtrHelper<QScopedPointer<qSlicerCoreApplicationPrivate, QScopedPointerDeleter<qSlicerCoreApplicationPrivate> > const> (ptr=...)
    at /usr/include/qt5/QtCore/qglobal.h:1143
#2  0x00007ffaf1672d29 in qSlicerCoreApplication::d_func (this=0x0) at /home/rafael/src/Slicer/Slicer/Base/QTCore/qSlicerCoreApplication.h:648
#3  0x00007ffaf166bb1f in qSlicerCoreApplication::userSettings (this=0x0) at /home/rafael/src/Slicer/Slicer/Base/QTCore/qSlicerCoreApplication.cxx:1167
#4  0x00007ffaf109ff26 in qSlicerTerminologyNavigatorWidget::~qSlicerTerminologyNavigatorWidget (this=0x562b38f69ef0, __in_chrg=<optimized out>)
    at /home/rafael/src/Slicer/Slicer/Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx:633
#5  0x00007ffaf10a0069 in qSlicerTerminologyNavigatorWidget::~qSlicerTerminologyNavigatorWidget (this=0x562b38f69ef0, __in_chrg=<optimized out>)
    at /home/rafael/src/Slicer/Slicer/Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx:636
#6  0x00007ffb1d4e6ba9 in qdesigner_internal::WidgetDataBase::defaultPropertyValues(QString const&) () from /usr/lib64/libQt5Designer.so.5
#7  0x00007ffb1d4e6de8 in qdesigner_internal::WidgetDataBase::grabDefaultPropertyValues() () from /usr/lib64/libQt5Designer.so.5
#8  0x0000562b374975f3 in ?? ()
#9  0x0000562b37490d3e in ?? ()
#10 0x0000562b3747ddf7 in ?? ()
#11 0x00007ffb1bbe87ed in __libc_start_main () from /lib64/libc.so.6
#12 0x0000562b3747defa in ?? ()
```
