### ISSUE TITLE
SimpleITK usage in Slicer broken as observed in `test_sitkUtils`

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#6598]
## Summary

SimpleITK usage in Slicer has had problems since the merging of 0d1ed30a34f96ad5c5f367626347bf5b3a4f1e95. This was also reported at https://discourse.slicer.org/t/sitkutils-pullvolumefromslicer-does-not-create-sitk-image-in-slicer-5-1/25669

This issue appears to be captured by Slicer failed test https://slicer.cdash.org/test/23247998

## Steps to reproduce

```
Python 3.9.10 (main, Oct 16 2022, 23:27:17) [MSC v.1930 64 bit (AMD64)] on win32
>>> import SimpleITK as sitk
>>> sitk.ReadImage(r"C:\Users\butlej30383\Downloads\MRHead.nrrd")
<SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'slicer_itk::simple::Image *' at 0x0000017A7A8B8E10> >
>>> image = sitk.ReadImage(r"C:\Users\butlej30383\Downloads\MRHead.nrrd")
>>> image
<SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'slicer_itk::simple::Image *' at 0x0000017A7A8B8F00> >
>>> image_array = sitk.GetArrayFromImage(image)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\butlej30383\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-15\lib\Python\Lib\site-packages\SimpleITK\extra.py", line 269, in GetArrayFromImage
    array_view = GetArrayViewFromImage(image)
  File "C:\Users\butlej30383\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-15\lib\Python\Lib\site-packages\SimpleITK\extra.py", line 255, in GetArrayViewFromImage
    image_memory_view = _GetMemoryViewFromImage(image)
TypeError: in method 'GetByteArrayFromImage', argument needs to be of type 'sitk::Image *'
>>> 
```

## Expected behavior

SimpleITK methods such as `GetArrayFromImage` should not return a traceback.

## Environment
- Slicer version: Slicer-5.1.0-2022-10-15
- Operating system: Windows

**Comment by jcfr** [comment]
Directly running the command generating `` return some useful warnings:

```bash
/home/jcfr/Projects/Slicer-Release/Swig-install/bin/swig \
  -python \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Common \
  -DSWIGWORDSIZE64 \
  -features \
  autodoc=1 \
  -keyword \
  -threads \
  -outdir \
  /home/jcfr/Projects/Slicer-Release/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITK \
  -c++ \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/Common/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/Registration/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/BasicFilters/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/IO/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK-build/SimpleITK-build/Code/BasicFilters/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK-build/SimpleITK-build/Code/Common/include \
  -I/home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Python \
  -o \
  /home/jcfr/Projects/Slicer-Release/SimpleITK-build/SimpleITK-build/Wrapping/Python/SimpleITKPYTHON_wrap.cxx \
  /home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Python/SimpleITK.i
```

Output:

```
/home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Python/Python.i:83: Warning 303: %extend defined for an undeclared class itk::simple::ProcessObject.
/home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Python/sitkTransform.i:134: Warning 303: %extend defined for an undeclared class itk::simple::Transform.
/home/jcfr/Projects/Slicer-Release/SimpleITK/Wrapping/Python/sitkImage.i:965: Warning 303: %extend defined for an undeclared class itk::simple::Image.
/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/Common/include/sitkPixelIDValues.h:125: Warning 509: Overloaded method slicer_itk::simple::GetPixelIDValueAsString(slicer_itk::simple::PixelIDValueEnum) effectively ignored,
/home/jcfr/Projects/Slicer-Release/SimpleITK/Code/Common/include/sitkPixelIDValues.h:124: Warning 509: as it is shadowed by slicer_itk::simple::GetPixelIDValueAsString(slicer_itk::simple::PixelIDValueType).
```
