### ISSUE TITLE
Support for building Slicer on Apple arm64

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6811]
This is meta issues aiming to organize the sub-tasks associated with arm64 support.

* [ ] https://github.com/Slicer/Slicer/issues/5944
* [ ] https://github.com/Slicer/slicer_download/issues/22
* [ ] https://github.com/Slicer/slicer_download_stats/issues/6

**Comment by pieper** [comment]
I was able to build Slicer current git (c6a6e4eb7aaa6be318b18438757d26e3f8510cfd) on a macbook Air M4. Homebrew versions of Qt and CMake.

Some small issues:
* Initial startup is very slow, probably due to shared libs, maybe just in debug mode.  Faster in restarts but still slow.
* The render views are blank at first, but resume to normal after changing the layout
* The mouse is "stuck" in the 3D view, always rotating
* Needed to turn off I18N due to bad path for Qt helper app
* Missing `pydicom` o WebServer and MultiVolumeImporter do not load

```
pieper@slate s % sw_vers
ProductName:		macOS
ProductVersion:		26.2
BuildVersion:		25C56

pieper@slate ~ % qmake --version
QMake version 3.1
Using Qt version 6.10.1 in /opt/homebrew/lib

pieper@slate ~ % cmake --version
cmake version 4.2.3
```

```
Make commands:
mkdir -p /opt/s
cd /opt/s
cmake \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DSlicer_REQUIRED_QT_VERSION="6.10" \
  -DCMAKE_BUILD_TYPE:STRING=Debug \
  -DSlicer_USE_SimpleITK:BOOL=OFF \
  -DSlicer_BUILD_I18N_SUPPORT:BOOL=OFF \
  -DSlicer_BUILD_DICOM_SUPPORT:BOOL=OFF \
  -DSlicer_VTK_SMP_IMPLEMENTATION_TYPE:STRING=Sequential \
  -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=26.2 \
  -DCMAKE_OSX_SYSROOT:STRING="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" \
  /Users/pieper/slicer/latest/Slicer
```

Then
```
make -j10
```

<img width="908" height="742" alt="Image" src="https://github.com/user-attachments/assets/51879df9-931b-4d88-8856-ef0358509efb" />

**Comment by pieper** [comment]
Also there is a crash when opening the File -> Save Data dialog.  See https://github.com/commontk/CTK/pull/1348

**Comment by joshuagantner** [comment]
Works on macOS 16.3.1 as well:

cmake \
-DCMAKE_OSX_ARCHITECTURES=arm64 \
-DSlicer_USE_SYSTEM_OpenSSL:BOOL=ON \
-DOPENSSL_ROOT_DIR:PATH=$(brew --prefix openssl@3) \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DSlicer_BUILD_WEBENGINE_SUPPORT:BOOL=OFF \
-DQt5_DIR:PATH=/opt/homebrew/opt/qt@5/lib/cmake/Qt5 \
-DCTKAppLauncher_DIR:PATH=/Users/joshuagantner/Development/SlicerBuild/CTKAppLauncherLib-build \
-DSlicer_USE_SYSTEM_QT:BOOL=ON \
-DSlicer_USE_SimpleITK:BOOL=OFF \
-DSlicer_BUILD_DICOM_SUPPORT:BOOL=OFF \
-S /Users/joshuagantner/Development/Slicer \
-B /Users/joshuagantner/Development/SlicerBuild

Had to change from URL to GIT in External_CTKAPPLAUNCHER.cmake:
replaced
      URL https://github.com/commontk/AppLauncher.git
      URL_HASH SHA256=${sha256}
with
      GIT_REPOSITORY "https://github.com/commontk/AppLauncher.git"
      GIT_TAG "v0.1.10"

<img width="663" height="118" alt="Image" src="https://github.com/user-attachments/assets/eebdcd2c-abd8-4427-97c9-035cf1c8ef33" />

**Comment by vcasellesb** [comment]
Hi! I saw recently that Apple is dropping Intel-based app support (Rosetta 2, which is used to run Slicer, I believe). Do you guys know if Slicer plans on releasing a "fully-native Silicon-based" version of the app?

**Comment by jamesobutler** [comment]
Yes, see comment at https://discourse.slicer.org/t/why-arent-we-building-the-extensions-in-parallel/47155/9?u=jamesobutler. There will be work to ultimately provided arm versions of Slicer across all platforms (Windows, macOS, Linux).

**Comment by vcasellesb** [comment]
Thanks so much for your reply @jamesobutler !

**Comment by w1ebr** [comment]
I am getting these errors in my build:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/scmake/Slicer-build/lib/Slicer-5.13/qt-scripted-modules/MultiVolumeImporterPlugin.py", line 4, in <module>
    import DICOMLib
ModuleNotFoundError: No module named 'DICOMLib'
[Qt] loadSourceAsModule - Failed to load file "/opt/scmake/Slicer-build/lib/Slicer-5.13/qt-scripted-modules/MultiVolumeImporterPlugin.py"  as module "MultiVolumeImporterPlugin" !
[Qt] Fail to instantiate module  "MultiVolumeImporterPlugin"
[Qt] The following modules failed to be instantiated:
[Qt]    MultiVolumeImporterPlugin
[Qt] Populating font family aliases took 40 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost. 
Loading Slicer RC file [/Users/gene/.slicerrc.py]

**Comment by w1ebr** [comment]
With sample data, I got this error:

"Volume" Reader has successfully read the file "/Users/gene/Library/Caches/slicer.org/Slicer/SlicerIO/DTI-Brain.nrrd" "[0.59s]"
Switch to module:  "VolumeRendering"
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
No scalars named "" or with id -1 found on input.
error: [/opt/scmake/Slicer-build/bin/Slicer.app/Contents/MacOS/./Slicer] exit abnormally - Report the problem.
