### ISSUE TITLE
Landmark Registration AttributeError in Slicer 5.4 developer mode

### ISSUE THREAD

**Issue by jamzad** [Slicer/Slicer#7194]
Hi

I just installed the 5.4.0 release and noticed that I cannot open Landmark Registration module when the developer mode is enabled. The error I'm getting is as follow:
```
Traceback (most recent call last):
  File "C:/Users/X/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/LandmarkRegistration.py", line 69, in setup
    self.reloadAndTestButton.toolTip = "Reload this module and then run the %s self test." % scenario
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'reloadAndTestButton'
Traceback (most recent call last):
  File "C:/Users/X/AppData/Local/slicer.org/Slicer 5.4.0/bin/../lib/Slicer-5.4/qt-scripted-modules/LandmarkRegistration.py", line 219, in enter
    self.interfaceFrame.enabled = False
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'interfaceFrame'
```

The module works properly when the developer mode is disabled. In the previous Slicer version (5.2.2) Landmark Registration works regardless of the developer mode status.

Thanks
Amoon

**Comment by pieper** [comment]
Thanks for the report - I noticed that too late for the release, but the current previews should be working.

https://github.com/pieper/CompareVolumes/commit/cb755dda78f726cf9262aa4e1f75122c72a0df2f

https://github.com/Slicer/Slicer/commit/8c92a12d6acecde092439981af70b1a27b6d2cf1

**Comment by jamzad** [comment]
Thank you Steve!

**Comment by dzenanz** [comment]
This happens with latest stable too:

```log
Session start time .......: 20240313_175006
Slicer version ...........: 5.6.1 (revision 32438 / 117ce5f) win-amd64 - installed release
Operating system .........: Windows /  Professional / (Build 22631, Code Page 65001) - 64-bit
Memory ...................: 65453 MB physical, 81837 MB virtual
CPU ......................: AuthenticAMD AMD Ryzen 9 5900 12-Core Processor             , 24 cores, 24 logical processors
VTK configuration ........: OpenGL2 rendering, TBB threading
Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
Internationalization .....: disabled, language=
Developer mode ...........: enabled
Application path .........: C:/Users/Dzenan/AppData/Local/slicer.org/Slicer 5.6.1/bin
Additional module paths ..: C:/Dev/SlicerANTsWasm/ITKANTsCommon, slicer.org/Extensions-32438/DebuggingTools/lib/Slicer-5.6/qt-scripted-modules, C:/Dev/Rivanna/MedSAMSlicer/MedSAM/MedSAMLite, C:/Dev/SlicerANTsWasm/ANTsRegistration, slicer.org/Extensions-32438/SegmentEditorExtraEffects/lib/Slicer-5.6/qt-loadable-modules, slicer.org/Extensions-32438/SegmentEditorExtraEffects/lib/Slicer-5.6/qt-scripted-modules, slicer.org/Extensions-32438/MarkupsToModel/lib/Slicer-5.6/qt-loadable-modules
Scripted subject hierarchy plugin registered: SegmentEditor
Scripted subject hierarchy plugin registered: SegmentStatistics
Switch to module:  "Welcome"
Switch to module:  "LandmarkRegistration"
Traceback (most recent call last):
  File "C:/Users/Dzenan/AppData/Local/slicer.org/Slicer 5.6.1/bin/../lib/Slicer-5.6/qt-scripted-modules/LandmarkRegistration.py", line 69, in setup
    self.reloadAndTestButton.toolTip = "Reload this module and then run the %s self test." % scenario
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'reloadAndTestButton'
Traceback (most recent call last):
  File "C:/Users/Dzenan/AppData/Local/slicer.org/Slicer 5.6.1/bin/../lib/Slicer-5.6/qt-scripted-modules/LandmarkRegistration.py", line 219, in enter
    self.interfaceFrame.enabled = False
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'interfaceFrame'
```

**Comment by jamesobutler** [comment]
Reopening this now based on the report in https://github.com/Slicer/ExtensionsIndex/pull/2049#issuecomment-2161439559. https://github.com/pieper/CompareVolumes/commit/cb755dda78f726cf9262aa4e1f75122c72a0df2f fixed a similar issue, but not that exact issue which was reported here.

Fix incoming: https://github.com/Slicer/LandmarkRegistration/pull/37
