### ISSUE TITLE
can't use concurrent code with PythonSlicer

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7445]
## Summary

It would be good to be able to delegate tasks to subprocesses using standard python constructs such as [concurrent futures](https://docs.python.org/3/library/concurrent.futures.html).  But currently the PythonSlicer is not initialized in a compatible way.

## Steps to reproduce

```
import concurrent.futures
import numpy
import os

executor = concurrent.futures.ProcessPoolExecutor(max_workers=1)

matrices = [numpy.random.random([190,190]) for i in range(1)]

print("Starting")
#executor.map(threadTask, dicom_files)
futures = [executor.submit(numpy.linalg.det, matrix) for matrix in matrices]
print("Done starting")

results = []
for future in concurrent.futures.as_completed(futures):
    results.append(future.result())

print(results)

```

On mac I get this error:

```
Starting
Done starting
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[FD] Traceback (most recent call last):
[FD]   File "<string>", line 1, in <module>
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
[FD]     exitcode = _main(fd, parent_sentinel)
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
[FD]     prepare(preparation_data)
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
[FD]     _fixup_main_from_path(data['init_main_from_path'])
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
[FD]     main_content = runpy.run_path(main_path,
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/runpy.py", line 268, in run_path
[FD]     return _run_module_code(code, init_globals, run_name,
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/runpy.py", line 97, in _run_module_code
[FD]     _run_code(code, mod_globals, init_globals,
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/lib/Python/lib/python3.9/runpy.py", line 87, in _run_code
[FD]     exec(code, run_globals)
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/bin/Python/slicer/slicerqt.py", line 211, in <module>
[FD]     _internalInstance = _Internal()
[FD]   File "/Applications/Slicer-5.4.0.app/Contents/bin/Python/slicer/slicerqt.py", line 139, in __init__
[FD]     setattr(slicer, 'app', _qSlicerCoreApplicationInstance)
[FD] NameError: name '_qSlicerCoreApplicationInstance' is not defined
```

On linux I get this error:
```
Starting
Process ForkProcess-1:
Done starting
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/Slicer-5.6.0-linux-amd64/lib/Python/lib/python3.9/multiprocessing/process.py", line 299, in _bootstrap
    util._close_stdin()
  File "/home/ubuntu/Downloads/Slicer-5.6.0-linux-amd64/lib/Python/lib/python3.9/multiprocessing/util.py", line 415, in _close_stdin
    sys.stdin.close()
AttributeError: 'PythonQtStdInRedirect' object has no attribute 'close'
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/home/ubuntu/Downloads/Slicer-5.6.0-linux-amd64/lib/Python/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/ubuntu/Downloads/Slicer-5.6.0-linux-amd64/lib/Python/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
On windows I get this error:
```
Starting
Done starting
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\piepe\AppData\Local\slicer.org\Slicer 5.6.0\lib\Python\Lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\piepe\AppData\Local\slicer.org\Slicer 5.6.0\lib\Python\Lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[FD] Traceback (most recent call last):
[FD]   File "<string>", line 5, in <module>
[FD]   File "<string>", line 212, in <module>
[FD]   File "<string>", line 177, in __init__
[FD] AttributeError: module 'qt' has no attribute 'QTimer'
[FD] Traceback (most recent call last):
[FD]   File "<string>", line 1, in <module>
[FD]   File "C:\Users\piepe\AppData\Local\slicer.org\Slicer 5.6.0\lib\Python\Lib\multiprocessing\spawn.py", line 96, in spawn_main
[FD]     assert is_forking(sys.argv), "Not forking"
[FD] AssertionError: Not forking
```

At least on mac, if I make this change this line:

https://github.com/Slicer/Slicer/blob/main/Base/Python/slicer/slicerqt.py#L212

To this, things work as expected:
```
try:
    _internalInstance = _Internal()
except NameError:
    # not running in Slicer, so ignore error
    pass
```
## Environment
- Slicer version: Slicer-5.4 or 5.6
- Operating system: all, but different results depending on OS.

**Comment by pieper** [comment]
@jcfr this is the issue I was describing during the dev call today.  It's not in my critical path but it would be nice to sort out sometime.

**Comment by benbennett** [comment]
Process.start() hangs: Slicer sets sys.executable to PythonSlicer launcher

  1. Process.start() spawns the child (the launcher) and blocks writing the
     pickled startup data into the spawn pipe.
  2. The child dies - spawn_main never runs - so nothing ever reads the pipe.
  3. The parent keeps the pipe's read end open, so the write never gets a
     BrokenPipeError and blocks forever
  Possible fix : multiprocessing.set_executable(real python.exe).
Ran into this when writing an extension just don't know where it would go in main slicer project
