### ISSUE TITLE
Fix regression related to loading of SegmentEditorSubjectHierarchyPlugin

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7476]
## Summary

Following the integration of https://github.com/Slicer/Slicer/pull/7358, Slicer reports this error at startup time:

```pytb
Traceback (most recent call last):
  File "/home/jcfr/Projects/Slicer-Release/Slicer-build/lib/Slicer-5.7/qt-scripted-modules/SegmentEditor.py", line 34, in setup
    scriptedPlugin.setPythonSource(SubjectHierarchyPlugins.SegmentEditorSubjectHierarchyPlugin.filePath)
AttributeError: module 'SubjectHierarchyPlugins' has no attribute 'SegmentEditorSubjectHierarchyPlugin'
Traceback (most recent call last):
  File "/home/jcfr/Projects/Slicer-Release/Slicer-build/lib/Slicer-5.7/qt-scripted-modules/SegmentStatistics.py", line 47, in setup
    scriptedPlugin.setPythonSource(SubjectHierarchyPlugins.SegmentStatisticsSubjectHierarchyPlugin.filePath)
AttributeError: module 'SubjectHierarchyPlugins' has no attribute 'SegmentStatisticsSubjectHierarchyPlugin'
```

Additionally, the test `py_SubjectHierarchyCorePluginsSelfTest` is now failing[^1][^2] on all platform.

[^1]: https://slicer.cdash.org/test/26236010
[^2]: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-12-15

## Steps to reproduce

Run test:

```
$ ctest -R py_SubjectHierarchyCorePluginsSelfTest -C Release
```

or start the application

```
$ ./Slicer
```

### Comparison of `lib/Slicer-X.Y/qt-scripted-modules/SubjectHierarchyPlugins` Before and After

<table>

<tr><th></th><th>Before</th><th>After</th></tr>

<tr>

<td>

Build tree

</td>

<td>

```
$ cd Slicer-build/lib/Slicer-5.6/qt-scripted-modules

$ find SubjectHierarchyPlugins
SubjectHierarchyPlugins
SubjectHierarchyPlugins/parameterNodeWrapper
SubjectHierarchyPlugins/parameterNodeWrapper/guiConnectors.py
SubjectHierarchyPlugins/parameterNodeWrapper/__init__.py
SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SegmentEditorSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/__init__.py
```

</td>

<td>

```
$ cd Slicer-build/lib/Slicer-5.7/qt-scripted-modules

$ find SubjectHierarchyPlugins
SubjectHierarchyPlugins
SubjectHierarchyPlugins/SubjectHierarchyPlugins
SubjectHierarchyPlugins/SubjectHierarchyPlugins/__init__.py
SubjectHierarchyPlugins/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/parameterNodeWrapper
SubjectHierarchyPlugins/parameterNodeWrapper/guiConnectors.py
SubjectHierarchyPlugins/parameterNodeWrapper/__init__.py
SubjectHierarchyPlugins/SegmentEditorSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/__init__.py

```

</td>

</tr>

<tr>

<td>

Install tree

</td>

<td>

```
$ cd Slicer-5.6.0-linux-amd64/lib/Slicer-5.6/qt-scripted-modules

$ find SubjectHierarchyPlugins
SubjectHierarchyPlugins
SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/parameterNodeWrapper
SubjectHierarchyPlugins/parameterNodeWrapper/guiConnectors.py
SubjectHierarchyPlugins/parameterNodeWrapper/__init__.py
SubjectHierarchyPlugins/SegmentEditorSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/__init__.py
SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py
```

</td>

<td>

```
$ cd Slicer-build/lib/Slicer-5.7/qt-scripted-modules

$ find SubjectHierarchyPlugins
SubjectHierarchyPlugins
SubjectHierarchyPlugins/parameterNodeWrapper
SubjectHierarchyPlugins/parameterNodeWrapper/guiConnectors.py
SubjectHierarchyPlugins/parameterNodeWrapper/__init__.py
SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SegmentEditorSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SubjectHierarchyPlugins
SubjectHierarchyPlugins/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py
SubjectHierarchyPlugins/SubjectHierarchyPlugins/__init__.py
SubjectHierarchyPlugins/__init__.py
```

</td>

</tr>

</table>

## Environment
- Slicer version: https://github.com/Slicer/Slicer/commit/1d77e473abebc3b554d886614e2958adff34e38e
- Operating system: All platforms

**Comment by jcfr** [comment]
Since I will not be able to address before the nightly build starts, for now I will revert the relocation.

**Comment by lassoan** [comment]
I have a fix, will send a PR in 5 minutes

**Comment by lassoan** [comment]
I see that you've just submitted a fix, too, I'll just comment there then
