### ISSUE TITLE
Some QActions in Slicer are created dynamically and are not assigned to any parent

### ISSUE THREAD

**Issue by jadh4v** [Slicer/Slicer#7881]
## Summary

QActions present in the *.ui files in Slicer will automatically have a parent https://github.com/Slicer/Slicer/blob/main/Base/QTApp/Resources/UI/qSlicerMainWindow.ui

However, some QActions in Slicer are created dynamically in C++ code, and are not assigned to any parent. This causes a problem when searching for them through findChild findChildren API in slicer.util.* or even directly through Qt API find functions. I Don't know if there are many of these but I found one here, when I was trying to hide the action:
https://github.com/Slicer/Slicer/blob/main/Base/QTGUI/qSlicerModuleSelectorToolBar.cxx#L109

While there are other ways to search for these items such as looking into `menu.actions()` list, I think not being able to find them through the parent-child hierarchy is an unintuitive / unexpected behavior. There are other places where such widgets are instantiated but never set to any parent. 

This may also have potential for memory leaks since Qt will not delete orphan QObjects.

## Steps to reproduce
1. Start 3D Slicer
2. Open python console window
3. Search for actions in menus like this:
```py
slicer.util.findChild(slicer.util.mainWindow(), "ModuleHomeAction")
```

output
```sh
QAction(0x22f2c698b40 text="Home" toolTip="Favorite module for easy access" shortcut=QKeySequence("Ctrl+H") menuRole=TextHeuristicRole visible=true) 
```

```py
slicer.util.findChild(slicer.util.mainWindow(), "ViewFindModuleAction")
```

output:
```sh

Traceback (most recent call last):
  File "C:\Users\shreeraj.jadhav\AppData\Local\slicer.org\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 335, in findChild
    child = findChildren(widget, name=name)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\shreeraj.jadhav\AppData\Local\slicer.org\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 339, in findChild
    raise RuntimeError(errorMessage)
RuntimeError: Widget named ViewFindModuleAction does not exist.

```

## Environment
- Slicer version: HEAD at e8a49d6659, but also reproducible in `5.7.0-2024-07-22`
- Operating system: tested on Windows 11 64-bit

**Comment by lassoan** [comment]
Why is it a problem that you cannot find a QAction? Are you thinking about collecting all keyboard shortcuts by iterating through all QAction objects? I'm not sure it would work, because there can be lots of overlaps (e.g., pressing the `space` key has completely different effects, depending on what state the application is and which widget has the focus). If you only enumerate QAction objects, you also misses all VTK GUI keyboard&mouse shortcuts.

**Comment by jadh4v** [comment]
I was searching for specific actions in order to hide/show them as part of a customized application. Not able to find some actions using Slicer provided API like `slicer.util.findChild(slicer.util.mainWindow(), "actionName")` I think makes these function less reliable and inconsistent. Some actions are found and some are not. It would be an improvement from a developer experience point-of-view to have all such Qt elements present in the GUI tree. I think this probably doesn't need immediate response or addressing but might be nice to track to see if it gathers more attention in the future.
